function ADAM_main
    
    % Create main figure
    mainFig = figure('Name', 'A.D.A.M - Avichay & Daniel Analysis Microplate reader', ...
        'Position', [100, 100, 450, 550], ... 
        'NumberTitle', 'off', ...
        'MenuBar', 'none', ...
        'Resize', 'on');

    % Create main panel
    mainPanel = uipanel(mainFig, 'Position', [0.02, 0.05, 0.94, 0.9], ...
        'Title', '', 'BorderType', 'none');
    
    % Title
    uicontrol(mainPanel, 'Style', 'text', ...
        'String', 'A.D.A.M - Avichay & Daniel Analysis Microplate reader', ...
        'Position', [20, 420, 390, 40], ...
        'FontSize', 14, 'FontWeight', 'bold', ...
        'BackgroundColor', get(mainPanel, 'BackgroundColor'));
    
    % Subtitle
    uicontrol(mainPanel, 'Style', 'text', ...
        'String', 'Biology Tools', ...
        'Position', [20, 390, 390, 25], ...
        'FontSize', 12, ...
        'BackgroundColor', get(mainPanel, 'BackgroundColor'));
    
    % Section 1: PlateReader
    uicontrol(mainPanel, 'Style', 'text', ...
        'String', 'PlaterReader', ...
        'Position', [95, 350, 260, 25], ...
        'FontSize', 16, 'FontWeight', 'bold', ...
        'BackgroundColor', get(mainPanel, 'BackgroundColor'), ...
        'HorizontalAlignment', 'center');
    
    % PlateReader buttons - centered
    uicontrol(mainPanel, 'Style', 'pushbutton', ...
        'String', 'Step 1: Data Preparation', ...
        'Position', [95, 310, 260, 35], ...
        'FontSize', 12, ...
        'Callback', @step1Callback);
    
    uicontrol(mainPanel, 'Style', 'pushbutton', ...
        'String', 'Step 2: Raw OD/LUC Analysis', ...
        'Position', [95, 270, 260, 35], ...
        'FontSize', 12, ...
        'Callback', @step2Callback);
    
    uicontrol(mainPanel, 'Style', 'pushbutton', ...
        'String', 'Step 3: Luciferase Analysis', ...
        'Position', [95, 230, 260, 35], ...
        'FontSize', 12, ...
        'Callback', @step3Callback);

    uicontrol(mainPanel, 'Style', 'pushbutton', ...
        'String', 'Step 4: Lum vs. OD ', ...
        'Position', [95, 190, 260, 35], ...
        'FontSize', 12, ...
        'Callback', @step4Callback);

    uicontrol(mainPanel, 'Style', 'pushbutton', ...
        'String', 'Step 5: 3D Lum vs. OD vs. Time', ...
        'Position', [95, 150, 260, 35], ...
        'FontSize', 12, ...
        'Callback', @step5Callback);
    
    % Status text area
    uicontrol(mainPanel, 'Style', 'text', ...
        'String', 'Status & Instructions:', ...
        'Position', [20, 110, 200, 20], ...
        'FontSize', 12, 'FontWeight', 'bold', ...
        'BackgroundColor', get(mainPanel, 'BackgroundColor'), ...
        'HorizontalAlignment', 'left');
    
    % Status text area
    statusText = uicontrol(mainPanel, 'Style', 'text', ...
        'String', ['Welcome to Avicii Analysis World!' newline newline ...
                  'Select a PlateReader analysis tool from above:' newline ...
                  '• Step 1: Data Preparation - Process Excel data' newline ...
                  '• Step 2: Raw OD/LUC Analysis - Create growth curves' newline ...
                  '• Step 3: Luciferase Analysis - Analyze luciferase data' newline ...
                  '• Step 4: Lum vs. OD - Compare luminescence vs optical density' newline ...
                  '• Step 5: 3D Analysis - Advanced 3D visualization'], ...
        'Position', [20, -40, 390, 150], ...
        'FontSize', 10, ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', [0.95, 0.95, 0.95]);
    
    % Store handles in guidata
    handles = struct('statusText', statusText, 'mainFig', mainFig);
    guidata(mainFig, handles);

    %% =======================================================================
    %% CALLBACK FUNCTIONS - SECTION 1 ONLY
    %% =======================================================================
    
    %% Callback Functions for PlateReader Analysis
    function step1Callback(~, ~)
        handles = guidata(mainFig);
        set(handles.statusText, 'String', 'Starting Step 1: Data Preparation...');
        drawnow;
        % Call growth analysis module
        growth_analysis_module.prepareDataGUI(mainFig);
    end
    
    function step2Callback(~, ~)
        handles = guidata(mainFig);
        set(handles.statusText, 'String', 'Starting Step 2: OD Growth Analysis...');
        drawnow;
        growth_analysis_module.analyzeODGUI(mainFig);
    end
    
    function step3Callback(~, ~)
        handles = guidata(mainFig);
        set(handles.statusText, 'String', 'Starting Step 3: Luciferase Analysis...');
        drawnow;
        growth_analysis_module.analyzeLuciferaseGUI(mainFig);
    end

    function step4Callback(~, ~)
        handles = guidata(mainFig);
        set(handles.statusText, 'String', 'Starting Step 4: Lum vs. OD Analysis...');
        drawnow;
        growth_analysis_module.analyzeLumVsODGUI(mainFig);
    end

    function step5Callback(~, ~)
        handles = guidata(mainFig);
        set(handles.statusText, 'String', 'Starting Step 5: 3D Lum vs. OD vs. Time Analysis...');
        drawnow;
        growth_analysis_module.analyze3DLumVsODGUI(mainFig);
    end
    
end